### ISSUE TITLE
Code Released

### ISSUE THREAD

**Issue by Qihe-Pan** [Maoxie/SynBody#1]

**Comment by Qihe-Pan** [comment]
Excuse me, when will the code be released? I am curious about how to use this dataset.

**Comment by wang-zm18** [comment]
The same question! Thank you in advance!

**Comment by maoXyzt** [comment]
Thanks for your attention!

The project has been officially released on another repo [SynBody/SynBody](https://github.com/SynBody/SynBody).

The codes, toolchain, dataset and more information could be found on our [project page](https://synbody.github.io)
